#DROP DATABASE DIET_MANAGEMENT;

CREATE DATABASE DIET_MANAGEMENT;
USE DIET_MANAGEMENT;

# Main tables
CREATE TABLE DIET
(
    Diet_name	CHAR(20),
    PRIMARY KEY (Diet_name)
);

CREATE TABLE PATIENT
(
	P_id		INT NOT NULL AUTO_INCREMENT,
	Fname		VARCHAR(15)	NOT NULL,
	Minit		CHAR,
	Lname		VARCHAR(15)	NOT NULL,
    Diet		CHAR(20),
    PRIMARY KEY (P_id),
    FOREIGN KEY (Diet) REFERENCES DIET(Diet_name)
);

CREATE TABLE INGREDIENT
(
    Ing_id	CHAR(20) NOT NULL,
    In_Stock INT,
    PRIMARY KEY (Ing_id)
);

CREATE TABLE FOOD
(
	F_id			CHAR(20) NOT NULL,
    Customizable	BOOLEAN,    
    Prepared		INT,
	PRIMARY KEY (F_id)
);

CREATE TABLE ADDON
(
    A_id	CHAR(20) NOT NULL,
    A_type	CHAR(20),
    PRIMARY KEY (A_id)
);


# Associative Tables

CREATE TABLE PATIENT_INGREDIENT
(
	PI_Pid		INT,
    PI_Ingid	CHAR(20),
	FOREIGN KEY(PI_Pid) REFERENCES PATIENT(P_id),
    FOREIGN KEY(PI_Ingid) REFERENCES INGREDIENT(Ing_id)
);

CREATE TABLE FOOD_INGREDIENT
(
	FI_Fid		CHAR(20),
    FI_Ingid	CHAR(20),
	FOREIGN KEY(FI_Fid) REFERENCES FOOD(F_id),
    FOREIGN KEY(FI_Ingid) REFERENCES INGREDIENT(Ing_id)
);

CREATE TABLE PATIENT_ADDON
(
	PA_Pid		INT,
    PA_Aid		CHAR(20),
	FOREIGN KEY(PA_Pid) REFERENCES PATIENT(P_id),
    FOREIGN KEY(PA_Aid) REFERENCES ADDON(A_id)
);

CREATE TABLE PATIENT_DIET
(
	PD_Pid		INT,
    PD_Dname	CHAR(20),
	FOREIGN KEY(PD_Pid) REFERENCES PATIENT(P_id),
    FOREIGN KEY(PD_Dname) REFERENCES DIET(Diet_name)
);

CREATE TABLE DIET_FOOD
(
	DF_Dname	CHAR(20),
    DF_Fid		CHAR(20),
	FOREIGN KEY(DF_Dname) REFERENCES DIET(Diet_name),
    FOREIGN KEY(DF_Fid) REFERENCES FOOD(F_id)
);

CREATE TABLE DIET_ADDON
(
	DA_Dname	CHAR(20),
    DA_Aid		CHAR(20),
	FOREIGN KEY(DA_Dname) REFERENCES DIET(Diet_name),
    FOREIGN KEY(DA_Aid) REFERENCES ADDON(A_id)
);