USE DIET_MANAGEMENT;

SELECT * FROM PATIENT;

SELECT * FROM INGREDIENT;
SELECT DISTINCT Ing_id, IN_STOCK FROM INGREDIENT WHERE IN_STOCK>0;

SELECT * FROM PATIENT_INGREDIENT;
SELECT * FROM FOOD_INGREDIENT;

SELECT Fname, Ing_id FROM PATIENT p, INGREDIENT i, PATIENT_INGREDIENT WHERE (p.P_id = PATIENT_INGREDIENT.PI_Pid AND i.Ing_id = PATIENT_INGREDIENT.PI_Ingid);