USE DIET;

SELECT * FROM PATIENT;

SELECT * FROM INGREDIENT;

SELECT * FROM PATIENT_INGREDIENT;

SELECT Fname, Ing_id FROM PATIENT p, INGREDIENT i, PATIENT_INGREDIENT
WHERE (p.P_id = PATIENT_INGREDIENT.PI_Pid 
AND i.Ing_id = PATIENT_INGREDIENT.PI_Ingid);

SELECT FI_Fid Food_Name, FI_Ingid Ingredient FROM FOOD_INGREDIENT
ORDER BY Food_Name, Ingredient;

